
export const BRAND = {
    oceanDeep: '#001220',
    oceanDark: '#00334e',
    oceanMid: '#0d5c75',
    oceanLight: '#1a8f9f',
    biolum: '#a8c5d4',       
    biolumSoft: '#c1dbe5',   
    biolumDim: '#547582',    
    sandGold: '#d4a574',
    sandLight: '#e8c4a0',
    sandDark: '#8b6342',
    goldShimmer: '#fcd34d', 
    coral: '#ff6b6b',
    seaweed: '#2ed573',
    success: '#22c55e',
    error: '#ef4444',
    warning: '#f59e0b',
    info: '#3b82f6',
};
export const LIGHT_THEME = {
    mode: 'light',
    background: '#f5f3ef',           
    backgroundSecondary: '#faf8f5',  
    backgroundTertiary: '#e8e4dc',   
    surface: '#ffffff',              
    surfaceElevated: '#ffffff',
    surfacePressed: '#f0ece3',
    text: '#1a1a1a',                 
    textSecondary: '#4a4a4a',        
    textMuted: '#6b7280',            
    textInverse: '#ffffff',
    primary: '#0d4a6f',
    primaryLight: '#1a6b8f',
    primaryDark: '#072d45',
    secondary: '#1a6b8f',
    secondaryLight: '#4a9bb8',
    accent: '#d4a574',
    accentDark: '#b8844c',
    border: 'rgba(0, 0, 0, 0.1)',
    borderStrong: 'rgba(0, 0, 0, 0.2)',
    glass: 'rgba(255, 255, 255, 0.95)',
    glassBorder: 'rgba(0, 0, 0, 0.08)',
    glassOverlay: 'rgba(255, 255, 255, 0.9)',
    shadowColor: '#000000',
    tabBar: 'rgba(255, 255, 255, 0.98)',
    tabBarBorder: 'rgba(0, 0, 0, 0.08)',
    tabInactive: 'rgba(255, 255, 255, 0.5)',
    tabActive: '#ffffff',
    card: '#ffffff',
    cardBorder: 'rgba(0, 0, 0, 0.08)',
    success: BRAND.success,
    error: BRAND.error,
    warning: BRAND.warning,
    info: BRAND.info,
};
export const DARK_THEME = {
    mode: 'dark',
    background: BRAND.oceanDeep,
    backgroundSecondary: '#001830',
    backgroundTertiary: '#002040',
    surface: '#0a1f2e',
    surfaceElevated: '#0d2a3d',
    surfacePressed: '#051520',
    text: '#ffffff',
    textSecondary: '#a8c5d4',
    textMuted: '#6b8a99',
    textInverse: '#1a1a1a',
    primary: BRAND.biolum,
    primaryLight: '#66ffff',
    primaryDark: BRAND.biolumDim,
    secondary: BRAND.oceanLight,
    secondaryLight: '#4ab5c5',
    accent: BRAND.sandGold,
    accentDark: BRAND.sandDark,
    border: 'rgba(255, 255, 255, 0.08)',
    borderStrong: 'rgba(255, 255, 255, 0.15)',
    glass: 'rgba(10, 31, 46, 0.85)',
    glassBorder: 'rgba(0, 255, 255, 0.15)',
    glassOverlay: 'rgba(0, 18, 32, 0.9)',
    shadowColor: '#000000',
    tabBar: 'rgba(10, 31, 46, 0.95)',
    tabBarBorder: 'rgba(0, 255, 255, 0.1)',
    tabInactive: '#4a6575',
    tabActive: BRAND.biolum,
    card: '#0a1f2e',
    cardBorder: 'rgba(0, 255, 255, 0.1)',
    success: BRAND.success,
    error: BRAND.error,
    warning: BRAND.warning,
    info: BRAND.info,
};
export const GRADIENTS = {
    primary: [BRAND.oceanMid, BRAND.oceanDark],
    oceanSurface: [BRAND.oceanMid, BRAND.oceanDark],
    oceanDeep: [BRAND.oceanDark, BRAND.oceanDeep],
    primaryButton: [BRAND.oceanMid, BRAND.oceanDark],
    gold: [BRAND.sandGold, BRAND.sandDark],
    biolum: [BRAND.biolum, BRAND.biolumDim],
};
export const TYPOGRAPHY = {
    hero: { fontSize: 40, fontWeight: '800', letterSpacing: -1 },
    h1: { fontSize: 32, fontWeight: '700', letterSpacing: -0.5 },
    h2: { fontSize: 24, fontWeight: '700', letterSpacing: -0.3 },
    h3: { fontSize: 20, fontWeight: '600' },
    h4: { fontSize: 18, fontWeight: '600' },
    body: { fontSize: 16, fontWeight: '400' },
    bodySmall: { fontSize: 14, fontWeight: '400' },
    caption: { fontSize: 12, fontWeight: '500' },
    overline: { fontSize: 10, fontWeight: '600', letterSpacing: 1.5, textTransform: 'uppercase' },
};
export const COLORS = {
    primary: BRAND.oceanDark,
    secondary: BRAND.oceanMid,
    accent: BRAND.sandGold,
    background: BRAND.oceanDeep,
    text: '#ffffff',
    textSecondary: '#a8c5d4',
    surface: '#0a1f2e',
};
export const createShadows = (isDark) => ({
    sm: {
        shadowColor: isDark ? '#000000' : '#000000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: isDark ? 0.3 : 0.08,
        shadowRadius: 3,
        elevation: 2,
    },
    md: {
        shadowColor: isDark ? '#000000' : '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: isDark ? 0.4 : 0.12,
        shadowRadius: 6,
        elevation: 4,
    },
    lg: {
        shadowColor: isDark ? '#000000' : '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: isDark ? 0.5 : 0.15,
        shadowRadius: 12,
        elevation: 8,
    },
    xl: {
        shadowColor: isDark ? '#000000' : '#000000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: isDark ? 0.6 : 0.2,
        shadowRadius: 24,
        elevation: 16,
    },
    glow: {
        shadowColor: isDark ? BRAND.biolum : BRAND.oceanMid,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.4,
        shadowRadius: 12,
        elevation: 8,
    },
});
