export const BEAC_MISSIONS = [
    { id: 1, name: "Playa Miramar" },
    { id: 2, name: "Playa Las Conchitas" },
    { id: 3, name: "Playa Hermosa" },
    { id: 4, name: "Playa Chica" },
    { id: 5, name: "Playa Grande" },
    { id: 6, name: "Punta Roquitas" },
    { id: 7, name: "La Pampilla" },
    { id: 8, name: "Waikiki" },
    { id: 9, name: "Makaha" },
    { id: 10, name: "Redondo" },
    { id: 11, name: "La Estrella" },
    { id: 12, name: "Las Cascadas" },
    { id: 13, name: "Barranquito" },
    { id: 14, name: "Los Pavos" },
    { id: 15, name: "Los Yuyos" },
    { id: 16, name: "Las Sombrillas" },
    { id: 17, name: "Agua Dulce" },
    { id: 18, name: "Pescadores" },
    { id: 19, name: "La Herradura" },
    { id: 20, name: "La Chira" },
    { id: 21, name: "Playa Venecia" },
    { id: 22, name: "Barlovento" },
    { id: 23, name: "San Pedro" },
    { id: 24, name: "Arica" },
    { id: 25, name: "Los Pulpos" },
    { id: 26, name: "El Silencio" },
    { id: 27, name: "Caballeros" },
    { id: 28, name: "Señoritas" },
    { id: 29, name: "Venice Beach" },
    { id: 30, name: "Santa Monica Beach" },
    { id: 31, name: "Malibu Beach" },
    { id: 32, name: "South Beach" },
    { id: 33, name: "Waikiki Beach" },
    { id: 34, name: "Laguna Beach" },
    { id: 35, name: "Coronado Beach" },
    { id: 36, name: "Clearwater Beach" },
    { id: 37, name: "Playa del Carmen" },
    { id: 38, name: "Cancún Beach" },
    { id: 39, name: "Tulum Beach" },
    { id: 40, name: "Playa Norte" },
    { id: 41, name: "Cabo San Lucas Beach" },
    { id: 42, name: "Puerto Vallarta Beach" },
    { id: 43, name: "Copacabana" },
    { id: 44, name: "Ipanema" },
    { id: 45, name: "Praia de Jericoacoara" },
    { id: 46, name: "Praia do Sancho" },
    { id: 47, name: "Baia do Sancho" },
    { id: 48, name: "Playa Blanca" },
    { id: 49, name: "Playa de Palomino" },
    { id: 50, name: "San Andrés Beach" },
    { id: 51, name: "Punta Cana Beach" },
    { id: 52, name: "Bavaro Beach" },
    { id: 53, name: "Flamenco Beach" },
    { id: 54, name: "Mar del Plata" },
    { id: 55, name: "Playa Bristol" },
    { id: 56, name: "Punta del Este" },
    { id: 57, name: "Playa Brava" },
    { id: 58, name: "Playa Anakena" },
    { id: 59, name: "Viña del Mar" },
    { id: 60, name: "Playa de la Concha" },
    { id: 61, name: "Playa de las Catedrales" },
    { id: 62, name: "Barceloneta Beach" },
    { id: 63, name: "Playa de Ses Illetes" },
    { id: 64, name: "Praia da Marinha" },
    { id: 65, name: "Praia de Benagil" },
    { id: 66, name: "Plage de Palombaggia" },
    { id: 67, name: "Plage de Pampelonne" },
    { id: 68, name: "Spiaggia dei Conigli" },
    { id: 69, name: "Navagio Beach" },
    { id: 70, name: "Elafonissi Beach" },
    { id: 71, name: "Jumeirah Beach" },
    { id: 72, name: "Sharm El Sheikh Beach" },
    { id: 73, name: "Agadir Beach" },
    { id: 74, name: "Qurum Beach" },
    { id: 75, name: "Palolem Beach" },
    { id: 76, name: "Anjuna Beach" },
    { id: 77, name: "Varkala Beach" },
    { id: 78, name: "Radhanagar Beach" },
    { id: 79, name: "Yalong Bay" },
    { id: 80, name: "Dadonghai Beach" },
    { id: 81, name: "Repulse Bay" },
    { id: 82, name: "Kenting Beach" }
];

export const getMissionName = (id) => {
    const mission = BEAC_MISSIONS.find(m => m.id === parseInt(id));
    return mission ? mission.name : `Misión #${id}`;
};
